### ISSUE TITLE
mmpycocotools安装问题

### ISSUE THREAD

**Issue by wind-waves-fll** [LeapLabTHU/ARC#11]
![image](https://github.com/LeapLabTHU/ARC/assets/143069182/90f36a67-c7e1-4cc1-9438-51734bcc65ee)
请问如何正确安装mmpycocotools库，查询资料后说安装cpython=0.29.33，但依旧无法解决，希望有好心人可以帮忙解决，真心的感谢。

**Comment by yifanpu001** [comment]
It seems like the math.h file is missing in your gcc. Have you try to reinstall the gcc in your environment?

**Comment by wind-waves-fll** [comment]
Thank you very much!
But I do the last step: pip install -v -e . face a question.
![628cd3479ffc6582c187b80d65ef9f9](https://github.com/LeapLabTHU/ARC/assets/143069182/3f4a3892-a157-4137-a28d-af40960d4bc5)
I need download nvcc? which version?

**Comment by yifanpu001** [comment]
this error may result from the inappropriate installation of the cuda driver/runtime. I think reinstall the cuda driver can handle this problem

**Comment by aimerlove4456** [comment]
![图片](https://github.com/LeapLabTHU/ARC/assets/104877157/fd2ea86e-2c58-4e7a-8dfb-79fbab57834f)
i also meet this problem ,but my cuda version the same with you 11.0

**Comment by aimerlove4456** [comment]
is this problem solved？ i also want to konw how to do when i meet the last step to pip install -v -e.

**Comment by yifanpu001** [comment]
maybe you can try to use the docker of mmdetection. that will solve all environment problems

**Comment by wind-waves-fll** [comment]
> is this problem solved？ i also want to konw how to do when i meet the last step to pip install -v -e.

Do you solve it? I need it very much

**Comment by aimerlove4456** [comment]
> > is this problem solved？ i also want to konw how to do when i meet the last step to pip install -v -e.
> 
> Do you solve it? I need it very much

yes,the cuda version is why the problem happen. Mabe you can try to re install cuda or use docker

**Comment by wind-waves-fll** [comment]
> > > is this problem solved？ i also want to konw how to do when i meet the last step to pip install -v -e.
> > 
> > 
> > Do you solve it? I need it very much
> 
> yes,the cuda version is why the problem happen. Mabe you can try to re install cuda or use docker

thank you! I success

**Comment by yifanpu001** [comment]
Good discussion! Could you please share your cuda versions? Maybe I can update the readme file to help other ones.
@wind-waves-fll @aimerlove4456

**Comment by wind-waves-fll** [comment]
> Good discussion! Could you please share your cuda versions? Maybe I can update the readme file to help other ones. @wind-waves-fll @aimerlove4456

my cuda is 11.8. I can say two question

First, add "pip3 install cython==0.29.33 -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com"  before "pip install mmpycocotools"

Second, when do the last "pip install -v -e ."  find the cuda's include dir no perssion，"chmod 755 include", then success.

**Comment by yifanpu001** [comment]
> my cuda is 11.8. I can say two question

apprecite it! i think this will help many guys
