### ISSUE TITLE
ImportError: /home/user1/SWC/ARC/mmdet/ops/corner_pool/corner_pool_ext.cpython-37m-x86_64-linux-gnu.so: file too short

### ISSUE THREAD

**Issue by aimerlove4456** [LeapLabTHU/ARC#12]
when i already finish the install and go to train，i run zhe code “python tools/train.py configs/obb/arc/arc_orcnn_r50fpn1x_ss_dota10_RxFFF_n4.py;”
i meet such a question “ImportError: /home/user1/SWC/ARC/mmdet/ops/corner_pool/corner_pool_ext.cpython-37m-x86_64-linux-gnu.so: file too short”

![图片](https://github.com/LeapLabTHU/ARC/assets/104877157/e08c5025-3a8b-413b-ac9d-6881ac7a131c)

**Comment by XiangtaoZheng** [comment]
I'm also having the same issue, it feels like there's an error in the CPP file, can the author help fix it

**Comment by yifanpu001** [comment]
it seems you have not install the mmdet properly
