### ISSUE TITLE
pretrained backbone

### ISSUE THREAD

**Issue by wind-waves-fll** [LeapLabTHU/ARC#13]
I want to request how to use pretrained backbone?
At the test code,I can see the load_checkpoint to load the model.
But when training, can I  how to use  pretrained backbone?

**Comment by wind-waves-fll** [comment]
I find the location!
in the defalt_runtime.py, set the  Load_from= pretrained backbone

**Comment by yifanpu001** [comment]
Hi, I think set the pretrained backbone dir in the model config file is a more elegent usage

https://github.com/LeapLabTHU/ARC/blob/4825acd8d5777d668ea4fb3b4d24aa53399d79ff/configs/obb/arc/arc_orcnn_r50fpn1x_ss_dota10_RxFFF_n4.py#L6

**Comment by wind-waves-fll** [comment]
> pretrained
ok,thank you very much!

**Comment by wind-waves-fll** [comment]
> Hi, I think set the pretrained backbone dir in the model config file is a more elegent usage
> 
> https://github.com/LeapLabTHU/ARC/blob/4825acd8d5777d668ea4fb3b4d24aa53399d79ff/configs/obb/arc/arc_orcnn_r50fpn1x_ss_dota10_RxFFF_n4.py#L6

Ok,thank you very much!
