### ISSUE TITLE
很感谢你的工作，想请教一下你最好的dota结果是：ARC-R50 81.77，test集是怎么进行测试的？

### ISSUE THREAD

**Issue by yhl2018** [LeapLabTHU/ARC#2]
我自己复现的结果只有79点多，所以想给你确认下test的分割方法和提交策略，是不是哪里不同，导致了结果的差异性

**Comment by yifanpu001** [comment]
Hi, we use multi-scale training and testing and more kernels to get the SOTA result. Thank for your concern, we will provide the multi-scale training and testing code soon.
