### ISSUE TITLE
Use for Yolo

### ISSUE THREAD

**Issue by liu15509348793** [LeapLabTHU/ARC#21]
Thank you very much for your work, I want to add the ARC module to yolo's backbone, how should I do it, can someone help me

**Comment by liu15509348793** [comment]
I just wanted to add somewhere, not replace the whole backbone

**Comment by yifanpu001** [comment]
just replace the conv2d layers with ARC layer

**Comment by liu15509348793** [comment]
> 只需将 conv2d 层替换为 ARC 层即可

Thank you for your reply, but I couldn't find the source code for the ARC layer, can you help me, thank you very much

**Comment by yifanpu001** [comment]
in this file #[https://github.com/LeapLabTHU/ARC/blob/4825acd8d5777d668ea4fb3b4d24aa53399d79ff/mmdet/models/backbones/modules/adaptive_rotated_conv.py#L127](url)
@liu15509348793

**Comment by liu15509348793** [comment]
> in this file #[https://github.com/LeapLabTHU/ARC/blob/4825acd8d5777d668ea4fb3b4d24aa53399d79ff/mmdet/models/backbones/modules/adaptive_rotated_conv.py#L127](url) @liu15509348793

Okay, thank you so much, I'm going to give it a try

**Comment by liu15509348793** [comment]
> in this file #[https://github.com/LeapLabTHU/ARC/blob/4825acd8d5777d668ea4fb3b4d24aa53399d79ff/mmdet/models/backbones/modules/adaptive_rotated_conv.py#L127](url) @liu15509348793

Is ARC only applicable to 3*3 convolution? If it is a 1*1 convolution, how should I modify the code?
