### ISSUE TITLE
use for FPS

### ISSUE THREAD

**Issue by ZYX214333** [LeapLabTHU/ARC#24]
Hello, I observed that the FPS of oriented rcnn r50 in your paper is 29.9, but I found that the FPS of the original oriented rcnn paper is only 15.5. Would you like to know what special standards are used in your FPS calculation?
![1](https://github.com/user-attachments/assets/c9b4fb36-35b6-4e07-b399-0a7e1ffdb650)
![9](https://github.com/user-attachments/assets/83e25031-9318-43c4-bf36-a9012567c9d6)

**Comment by yifanpu001** [comment]
different GPU
