### ISSUE TITLE
关于测试时命令行中的save_dir

### ISSUE THREAD

**Issue by Boooil** [LeapLabTHU/ARC#5]
> python tools/test.py configs/obb/arc/arc_orcnn_r50fpn1x_ss_dota10_RxFFF_n4.py \
YOUR_CHECKPOINT_PATH --format-only --options save_dir=YOUR_SAVE_DIR;

作者您好，感谢您的开源代码，我在执行测试命令时，其中的--options后跟的save_dir配置，我不是很明白它的功能是什么，想请您解答一下。

**Comment by yifanpu001** [comment]
The directory to save test results.
