### ISSUE TITLE
关于Merging patch bboxes into full image阶段task速度变为0的问题

### ISSUE THREAD

**Issue by Boooil** [LeapLabTHU/ARC#6]
![image](https://github.com/LeapLabTHU/ARC/assets/42399437/06254ae8-155c-4513-a303-733c766038c3)

您好，我执行测试命令时，在Merging patch bboxes into full image阶段task处理速度变为0，如图所示。
我在github上搜索相关issues，有解决方案提到“在--options后面增加nproc=1或直接在代码中将nproc改为1，我看到ARC仓库的代码中已经有相关的修改了，实际执行的时候也是single processing。
![image](https://github.com/LeapLabTHU/ARC/assets/42399437/61b5813f-26af-4f96-962b-d9ba8ebffdca)
(https://github.com/jbwang1997/OBBDetection/blob/master/mmdet/datasets/obb/dota.py#L76)

我的电脑显卡是3060 laptop版本，请问作者在执行的时候有碰到过这种问题吗？这种问题是否是因为电脑配置低问题引起的？
我观察到从task从7到9是在缓慢执行的，但是速度实在是太慢了，到9就基本上卡住很长时间。

**Comment by yifanpu001** [comment]
I'm sorry, I have never encountered this problem.

**Comment by Boooil** [comment]
that's okey, I will search for more information on the Internet to solve this problem, thanks anyway :）
