### ISSUE TITLE
Which dataset does the ARC-ResNet pretrain on? And if I wanna to do some modification，should I do pretrain again?

### ISSUE THREAD

**Issue by kouyuanbo** [LeapLabTHU/ARC#7]
Which dataset does the ARC-ResNet pretrain on? And if I wanna to do some modification，should I do pretrain again?

**Comment by yifanpu001** [comment]
For question 1, please refer to #3 
For question 2, If you do not modify the backbone part, I think you don't need to pretrain the backbone again. If you modify the backbone part, I think it depends on your way of modification.

**Comment by kouyuanbo** [comment]
> For question 1, please refer to #3 For question 2, If you do not modify the backbone part, I think you don't need to pretrain the backbone again. If you modify the backbone part, I think it depends on your way of modification.

ok. Thanks for your answer.
